### PR TITLE
Create test for failing decoding of request

### PR DESCRIPTION
**Pull request by lucacorti**

### CODE REVIEW

**Comment by lucacorti** [comment]
I've created a test to simulate the failed parsing of the response I get from my nginx server. Without  any networking code, I just embedded the binary dump of the response.

**Comment by nesQuick** [comment]
Hey @lucacorti thanks for providing the failing test. I won't merge this into master, but it's a great starting point to inspect what is actually going on while parsing the hbf. Also if you'd like to dig into the issue, and have questions about the pack implementation, please always feel free to ask. You could find me in the elixir slack

**Comment by nesQuick** [comment]
Hey @lucacorti after i really digged into the issue here is what I found:

The header in question is a "Literal Header Field with Incremental Indexing — Indexed Name"

With the following binary layout:
```
  0   1   2   3   4   5   6   7
+---+---+---+---+---+---+---+---+
| 0 | 1 |      Index (6+)       |
+---+---+-----------------------+
| H |     Value Length (7+)     |
+---+---------------------------+
| Value String (Length octets)  |
+-------------------------------+
```

The Index is a `27` which is regarding to the hbf-table a `content-language` header w/o value. Now let's take a look at the string parsing which is called with

```
<<117, 247, 228, 145, 246, 86, 19, 141, 127, 63, 0, 137, 25, 8, 90, 210, 181, 131, 170, 98, 163, 132, 143, 210, 74, 143>>
```

First byte is `01110101` thus it's a non-huffman encoded string. Which makes reasoning about the following lines easier.

```
+---+---+-----------------------+
| H |     Value Length (7+)     |
+---+---------------------------+
| Value String (Length octets)  |
+-------------------------------+
```

7-bit encoded length from `01110101` is *117* and this leads us to the problem: The remaining hbf is just not long enough:

```elixir
iex(2)> byte_size(<<247, 228, 145, 246, 86, 19, 141, 127, 63, 0, 137, 25, 8, 90, 210, 181, 131, 170, 98, 163, 132, 143, 210, 74, 143>>)
25
```

And that is why we see the match error because elixir tries to read 117 bytes but there are only 25 left to read from.

That is why I wonder what is going on there, either the test data misses something, or nginx is sending something wired here.

I've two ideas how to proceed from here, but frankly I do not have the resources to follow any of them:

1. Try a different http/2 client and make the exact same request and see if that works. I'd be interested what the `content-language` actually should be.
2. Similar to 1. try if a different HPACK implementation can parse the HBF, you could for example try the one cowboy uses from cowlib

Please let me know if you have any new findings, as I'm be really keen to have a good HPACK implementation here.

cheers,

OT: it seems that this is not the first request on the connection, it refers to a hbf-table index of `126` which seems quite high to me, but also results in a `:none` tuple in the header list.

**Comment by lucacorti** [comment]
Thanks for taking the time to analyze this. I'll be digging into it following your suggestions and report any finding. This is actually the first request on the connection though, so I guess there's something odd going on.

**Comment by nesQuick** [comment]
Awesome, I'm always happy to help. I can not guarantee that it's not a bug in the `elixir-hpack` code.

**Comment by lucacorti** [comment]
Apparently curl has no issue with parsing the response:
```
$ /usr/local/bin/curl -v --http2 https://www.fantacast.it
* Rebuilt URL to: https://www.fantacast.it/
*   Trying 185.92.223.168...
* Connected to www.fantacast.it (185.92.223.168) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: /usr/local/etc/openssl/cert.pem
  CApath: none
* TLSv1.2 (OUT), TLS header, Certificate Status (22):
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Client hello (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS change cipher, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256
* ALPN, server accepted to use h2
* Server certificate:
*  subject: CN=fantacast.it
*  start date: Jul 16 21:04:00 2016 GMT
*  expire date: Oct 14 21:04:00 2016 GMT
*  subjectAltName: host "www.fantacast.it" matched cert's "www.fantacast.it"
*  issuer: C=US; O=Let's Encrypt; CN=Let's Encrypt Authority X3
*  SSL certificate verify ok.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* TCP_NODELAY set
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x7f8ea300de00)
> GET / HTTP/1.1
> Host: www.fantacast.it
> User-Agent: curl/7.50.1
> Accept: */*
> 
* Connection state changed (MAX_CONCURRENT_STREAMS updated)!
< HTTP/2 200 
< server: nginx/1.11.3
< date: Tue, 30 Aug 2016 18:13:30 GMT
< content-type: text/html
< content-length: 612
< last-modified: Thu, 28 Jul 2016 10:25:23 GMT
< etag: "5799dd93-264"
< accept-ranges: bytes
< 
<!DOCTYPE html>
<html>
<head>
<title>Welcome to nginx!</title>
<style>
    body {
        width: 35em;
        margin: 0 auto;
        font-family: Tahoma, Verdana, Arial, sans-serif;
    }
</style>
</head>
<body>
<h1>Welcome to nginx!</h1>
<p>If you see this page, the nginx web server is successfully installed and
working. Further configuration is required.</p>

<p>For online documentation and support please refer to
<a href="http://nginx.org/">nginx.org</a>.<br/>
Commercial support is available at
<a href="http://nginx.com/">nginx.com</a>.</p>

<p><em>Thank you for using nginx.</em></p>
</body>
</html>
* Connection #0 to host www.fantacast.it left intact
```

**Comment by lucacorti** [comment]
This looks strange because neither `curl` nor `chrome` parsed responses contains a content-language header. These are the response headers as seen by `chrome`:

```
content-encoding:gzip
content-type:text/html
date:Wed, 31 Aug 2016 12:55:21 GMT
etag:W/"5799dd93-264"
last-modified:Thu, 28 Jul 2016 10:25:23 GMT
server:nginx/1.11.3
status:200
```

**Comment by nesQuick** [comment]
I just realised that I missed one piece of information from my debugging journey

```
[:none, {":status", "400"}, {"server", "etag"}, {"last-modified", "Thu, 28 Jul 2016 10:25:23 GMT"}, {"content-length", "612"}, {"content-type", "text/html"}, {"date", "Mon, 01 Aug 2016 23:12:32 GMT"}, {"server", "nginx/1.11.3"}, {":status", "200"}]
IDX: 27
REST: <<117, 247, 228, 145, 246, 86, 19, 141, 127, 63, 0, 137, 25, 8, 90, 210, 181, 131, 170, 98, 163, 132, 143, 210, 74, 143>>
LENGTH: 117
```

the first line was the headers parsed before the crash
IDX is the index from the "Literal Header Field with Incremental Indexing — Indexed Name
REST is the rest passed into the parse_string function
LENGTH is what the parse_string function found as string length

Two things I observed here, first the `:none` header I mentioned before, and 2nd two status headers, so yeah, maybe there is something going wrong before. Could you verify that you pass the same hbf to hpack as curl is using? or as chrome receives? the headers frame can be split AFAIR maybe you are not passing all of it?

**Comment by lucacorti** [comment]
Yes, that looks strange. My code does HBF reassembly, but the frame in the response is a HEADERS frame with the END_HEADERS flag set, so it should contain a full HBF.

```
%Http2.Frame{flags: %Http2.Frame.Headers.Flags{end_headers: true,
  end_stream: false, padded: false, priority: false}, length: 108,
 payload: %Http2.Frame.Headers.Payload{exclusive: false,
  header_block_fragment: <<136, 118, 137, 170, 99, 85, 229, 128, 174, 16, 174,
    207, 97, 150, 228, 89, 62, 148, 100, 42, 67, 108, 202, 8, 1, 113, 64, 189,
    112, 13, 220, 100, 10, 98, 209, 191, 95, 135, 73, 124, 165, 137, 211, 77,
    31, ...>>, pad_length: 0, stream_dependency: 0, weight: 0}, stream_id: 1,
 type: :headers}
```

**Comment by lucacorti** [comment]
Also the `{"server", "etag"}` header looks wrong.

**Comment by lucacorti** [comment]
cURL has a trace option:

```
<= Recv header, 13 bytes (0xd)
0000: 48 54 54 50 2f 32 20 32 30 30 20 0d 0a          HTTP/2 200 ..
<= Recv header, 22 bytes (0x16)
0000: 73 65 72 76 65 72 3a 20 6e 67 69 6e 78 2f 31 2e server: nginx/1.
0010: 31 31 2e 33 0d 0a                               11.3..
<= Recv header, 37 bytes (0x25)
0000: 64 61 74 65 3a 20 57 65 64 2c 20 33 31 20 41 75 date: Wed, 31 Au
0010: 67 20 32 30 31 36 20 31 38 3a 32 36 3a 34 34 20 g 2016 18:26:44 
0020: 47 4d 54 0d 0a                                  GMT..
<= Recv header, 25 bytes (0x19)
0000: 63 6f 6e 74 65 6e 74 2d 74 79 70 65 3a 20 74 65 content-type: te
0010: 78 74 2f 68 74 6d 6c 0d 0a                      xt/html..
<= Recv header, 21 bytes (0x15)
0000: 63 6f 6e 74 65 6e 74 2d 6c 65 6e 67 74 68 3a 20 content-length: 
0010: 36 31 32 0d 0a                                  612..
<= Recv header, 46 bytes (0x2e)
0000: 6c 61 73 74 2d 6d 6f 64 69 66 69 65 64 3a 20 54 last-modified: T
0010: 68 75 2c 20 32 38 20 4a 75 6c 20 32 30 31 36 20 hu, 28 Jul 2016 
0020: 31 30 3a 32 35 3a 32 33 20 47 4d 54 0d 0a       10:25:23 GMT..
<= Recv header, 22 bytes (0x16)
0000: 65 74 61 67 3a 20 22 35 37 39 39 64 64 39 33 2d etag: "5799dd93-
0010: 32 36 34 22 0d 0a                               264"..
<= Recv header, 22 bytes (0x16)
0000: 61 63 63 65 70 74 2d 72 61 6e 67 65 73 3a 20 62 accept-ranges: b
0010: 79 74 65 73 0d 0a                               ytes..
<= Recv header, 2 bytes (0x2)
0000: 0d 0a                                           ..
```

**Comment by lucacorti** [comment]
Both curl and your implementation can parse `https://www.google.it` response, which also sends a single HEADERS frame with END_HEADERS set:

```
<= Recv header, 13 bytes (0xd)
0000: 48 54 54 50 2f 32 20 32 30 30 20 0d 0a          HTTP/2 200 ..
<= Recv header, 37 bytes (0x25)
0000: 64 61 74 65 3a 20 54 68 75 2c 20 30 31 20 53 65 date: Thu, 01 Se
0010: 70 20 32 30 31 36 20 30 37 3a 35 35 3a 30 34 20 p 2016 07:55:04 
0020: 47 4d 54 0d 0a                                  GMT..
<= Recv header, 13 bytes (0xd)
0000: 65 78 70 69 72 65 73 3a 20 2d 31 0d 0a          expires: -1..
<= Recv header, 35 bytes (0x23)
0000: 63 61 63 68 65 2d 63 6f 6e 74 72 6f 6c 3a 20 70 cache-control: p
0010: 72 69 76 61 74 65 2c 20 6d 61 78 2d 61 67 65 3d rivate, max-age=
0020: 30 0d 0a                                        0..
<= Recv header, 45 bytes (0x2d)
0000: 63 6f 6e 74 65 6e 74 2d 74 79 70 65 3a 20 74 65 content-type: te
0010: 78 74 2f 68 74 6d 6c 3b 20 63 68 61 72 73 65 74 xt/html; charset
0020: 3d 49 53 4f 2d 38 38 35 39 2d 31 0d 0a          =ISO-8859-1..
<= Recv header, 116 bytes (0x74)
0000: 70 33 70 3a 20 43 50 3d 22 54 68 69 73 20 69 73 p3p: CP="This is
0010: 20 6e 6f 74 20 61 20 50 33 50 20 70 6f 6c 69 63  not a P3P polic
0020: 79 21 20 53 65 65 20 68 74 74 70 73 3a 2f 2f 77 y! See https://w
0030: 77 77 2e 67 6f 6f 67 6c 65 2e 63 6f 6d 2f 73 75 ww.google.com/su
0040: 70 70 6f 72 74 2f 61 63 63 6f 75 6e 74 73 2f 61 pport/accounts/a
0050: 6e 73 77 65 72 2f 31 35 31 36 35 37 3f 68 6c 3d nswer/151657?hl=
0060: 65 6e 20 66 6f 72 20 6d 6f 72 65 20 69 6e 66 6f en for more info
0070: 2e 22 0d 0a                                     ."..
<= Recv header, 13 bytes (0xd)
0000: 73 65 72 76 65 72 3a 20 67 77 73 0d 0a          server: gws..
<= Recv header, 33 bytes (0x21)
0000: 78 2d 78 73 73 2d 70 72 6f 74 65 63 74 69 6f 6e x-xss-protection
0010: 3a 20 31 3b 20 6d 6f 64 65 3d 62 6c 6f 63 6b 0d : 1; mode=block.
0020: 0a                                              .
<= Recv header, 29 bytes (0x1d)
0000: 78 2d 66 72 61 6d 65 2d 6f 70 74 69 6f 6e 73 3a x-frame-options:
0010: 20 53 41 4d 45 4f 52 49 47 49 4e 0d 0a           SAMEORIGIN..
<= Recv header, 225 bytes (0xe1)
0000: 73 65 74 2d 63 6f 6f 6b 69 65 3a 20 4e 49 44 3d set-cookie: NID=
0010: 38 35 3d 45 36 37 43 49 62 65 5f 54 77 4a 33 2d 85=E67CIbe_TwJ3-
0020: 5a 5a 79 54 37 4f 6d 7a 39 4c 6f 32 44 71 48 38 ZZyT7Omz9Lo2DqH8
0030: 69 57 6b 61 39 49 68 57 4d 4e 7a 53 46 42 68 4b iWka9IhWMNzSFBhK
0040: 59 53 37 72 75 36 54 42 72 39 77 6b 68 59 67 42 YS7ru6TBr9wkhYgB
0050: 45 77 6c 4d 6d 62 33 49 77 37 4e 75 51 70 43 67 EwlMmb3Iw7NuQpCg
0060: 53 37 56 34 63 4c 4a 61 37 78 49 52 58 78 72 46 S7V4cLJa7xIRXxrF
0070: 64 59 75 7a 33 38 62 37 68 76 37 46 79 4c 75 2d dYuz38b7hv7FyLu-
0080: 69 64 59 67 6b 6e 38 56 57 56 46 55 38 46 41 6d idYgkn8VWVFU8FAm
0090: 2d 46 69 3b 20 65 78 70 69 72 65 73 3d 46 72 69 -Fi; expires=Fri
00a0: 2c 20 30 33 2d 4d 61 72 2d 32 30 31 37 20 30 37 , 03-Mar-2017 07
00b0: 3a 35 35 3a 30 34 20 47 4d 54 3b 20 70 61 74 68 :55:04 GMT; path
00c0: 3d 2f 3b 20 64 6f 6d 61 69 6e 3d 2e 67 6f 6f 67 =/; domain=.goog
00d0: 6c 65 2e 69 74 3b 20 48 74 74 70 4f 6e 6c 79 0d le.it; HttpOnly.
00e0: 0a                                              .
<= Recv header, 30 bytes (0x1e)
0000: 61 6c 74 65 72 6e 61 74 65 2d 70 72 6f 74 6f 63 alternate-protoc
0010: 6f 6c 3a 20 34 34 33 3a 71 75 69 63 0d 0a       ol: 443:quic..
<= Recv header, 60 bytes (0x3c)
0000: 61 6c 74 2d 73 76 63 3a 20 71 75 69 63 3d 22 3a alt-svc: quic=":
0010: 34 34 33 22 3b 20 6d 61 3d 32 35 39 32 30 30 30 443"; ma=2592000
0020: 3b 20 76 3d 22 33 36 2c 33 35 2c 33 34 2c 33 33 ; v="36,35,34,33
0030: 2c 33 32 2c 33 31 2c 33 30 22 0d 0a             ,32,31,30"..
<= Recv header, 21 bytes (0x15)
0000: 61 63 63 65 70 74 2d 72 61 6e 67 65 73 3a 20 6e accept-ranges: n
0010: 6f 6e 65 0d 0a                                  one..
<= Recv header, 23 bytes (0x17)
0000: 76 61 72 79 3a 20 41 63 63 65 70 74 2d 45 6e 63 vary: Accept-Enc
0010: 6f 64 69 6e 67 0d 0a                            oding..
<= Recv header, 2 bytes (0x2)
0000: 0d 0a  
```

**Comment by lucacorti** [comment]
Cowlib can also parse this correctly:

```
iex(6)> state = :cow_hpack.init(4_096)
{:state, 0, 4096, []}
iex(7)> :cow_hpack.decode(<<136, 118, 137, 170, 99, 85, 229, 128, 174, 16, 174, 207, 97, 150, 208, 122, 190, 148, 0, 84, 134, 217, 148, 16, 2, 226, 130, 102, 227, 46, 92, 101, 229, 49,
104, 223, 95, 135, 73, 124, 165, 137, 211, 77, 31, 92, 3, 54, 49, 50, 108, 150, 223, 61, 191, 74, 9, 229, 50, 219, 66, 130, 0, 92, 80, 32, 184, 38, 238, 9, 149, 49, 104, 223, 0, 131, 42
, 71, 55, 140, 254, 91, 117, 247, 228, 145, 246, 86, 19, 141, 127, 63, 0, 137, 25, 8, 90, 210, 181, 131, 170, 98, 163, 132, 143, 210, 74, 143>>, state)
{[{":status", "200"}, {"server", "nginx/1.11.3"},
  {"date", "Mon, 01 Aug 2016 23:36:38 GMT"}, {"content-type", "text/html"},
  {"content-length", "612"}, {"last-modified", "Thu, 28 Jul 2016 10:25:23 GMT"},
  {"etag", "\"5799dd93-264\""}, {"accept-ranges", "bytes"}],
 {:state, 291, 4096,

  [{74, {"last-modified", "Thu, 28 Jul 2016 10:25:23 GMT"}},
   {49, {"content-length", "612"}}, {53, {"content-type", "text/html"}},
   {65, {"date", "Mon, 01 Aug 2016 23:36:38 GMT"}},
   {50, {"server", "nginx/1.11.3"}}]}}
```

**Comment by lucacorti** [comment]
I'm adding debug to your code. Things seem to start going south after the `last-modified` header:

```
12:05:09.814 [debug] Indexed HF
{":status", "200"}

12:05:09.814 [debug] Literal HF with Incremental Indexing - Indexed
{54,
 <<137, 170, 99, 85, 229, 128, 174, 16, 174, 207, 97, 150, 195, 97, 190, 148, 0,
   148, 220, 90, 212, 16, 2, 226, 129, 5, 192, 55, 112, 15, 169, 139, 70, 255,
   95, 135, 73, 124, 165, 137, 211, 77, 31, 92, 3, 54, 49, 50, 108, ...>>}
{"server", "nginx/1.11.3"}

12:05:09.814 [debug] Literal HF with Incremental Indexing - Indexed
{33,
 <<150, 195, 97, 190, 148, 0, 148, 220, 90, 212, 16, 2, 226, 129, 5, 192, 55,

   112, 15, 169, 139, 70, 255, 95, 135, 73, 124, 165, 137, 211, 77, 31, 92, 3,
   54, 49, 50, 108, 150, 223, 61, 191, 74, 9, 229, 50, 219, 66, 130, ...>>}
{"date", "Fri, 02 Sep 2016 10:05:09 GMT"}

12:05:09.815 [debug] Literal HF with Incremental Indexing - Indexed
{31,
 <<135, 73, 124, 165, 137, 211, 77, 31, 92, 3, 54, 49, 50, 108, 150, 223, 61,
   191, 74, 9, 229, 50, 219, 66, 130, 0, 92, 80, 32, 184, 38, 238, 9, 149, 49,
   104, 223, 0, 131, 42, 71, 55, 140, 254, 91, 117, 247, 228, 145, ...>>}
{"content-type", "text/html"}

12:05:09.815 [debug] Literal HF with Incremental Indexing - Indexed
{28,
 <<3, 54, 49, 50, 108, 150, 223, 61, 191, 74, 9, 229, 50, 219, 66, 130, 0, 92,
   80, 32, 184, 38, 238, 9, 149, 49, 104, 223, 0, 131, 42, 71, 55, 140, 254, 91,
   117, 247, 228, 145, 246, 86, 19, 141, 127, 63, 0, 137, 25, ...>>}
{"content-length", "612"}

12:05:09.815 [debug] Literal HF with Incremental Indexing - Indexed
{44,
 <<150, 223, 61, 191, 74, 9, 229, 50, 219, 66, 130, 0, 92, 80, 32, 184, 38, 238,
   9, 149, 49, 104, 223, 0, 131, 42, 71, 55, 140, 254, 91, 117, 247, 228, 145,
   246, 86, 19, 141, 127, 63, 0, 137, 25, 8, 90, 210, 181, 131, ...>>}
{"last-modified", "Thu, 28 Jul 2016 10:25:23 GMT"}

12:05:09.815 [debug] Literal HF without Incremental Indexing - Indexed
{0,
 <<131, 42, 71, 55, 140, 254, 91, 117, 247, 228, 145, 246, 86, 19, 141, 127, 63,
   0, 137, 25, 8, 90, 210, 181, 131, 170, 98, 163, 132, 143, 210, 74, 143>>}
{"server", "etag"}

12:05:09.816 [debug] Indexed HF
{":status", "400"}

12:05:09.816 [debug] Indexed HF
:none

12:05:09.816 [debug] Literal HF with Incremental Indexing - Indexed
{27,
 <<117, 247, 228, 145, 246, 86, 19, 141, 127, 63, 0, 137, 25, 8, 90, 210, 181,
   131, 170, 98, 163, 132, 143, 210, 74, 143>>}
```

**Comment by nesQuick** [comment]
Awesome, could you share a patch of the debug code, please?

**Comment by nesQuick** [comment]
What kind of stands out to me is that `etag` header

> {"etag", "\"5799dd93-264\""}

Whatever this escaped quotes stuff is, seems wired.

**Comment by lucacorti** [comment]
Don't think that is escaped, it's just `IO.inspect` escaping quotes in the string output

**Comment by lucacorti** [comment]
The issue seems to be the `0b1000` at the beginning of the rest after parsing last modified. Since it begins with `1` it is parsed as a Indexed Header Field, but it actually isn't. If you remove that, you get `b1100100`. That also explain the trailing 4 bits at the end and everithing is byte aligned.

**Comment by nesQuick** [comment]
That sounds absolutely reasonable. But I wonder why it is there. Because partying strings ensure the rest is binary

**Comment by lucacorti** [comment]
There seems to be an extra `0` inserted in `parse string` after deconstruction. See updated debug code.

**Comment by nesQuick** [comment]
The `0b1000` is not a problem, elixir just hides any leading `0` so `0b1000` is `0b00001000`

```elixir
iex(3)> 0b1000 == 0b00001000
true
```

**BUT** you are right, on the end. There is this 4-bit sequence at the end, which also confuses me and I've no idea where this is coming from

**Comment by nesQuick** [comment]
I have to correct myself: The `size(4)` is not at all suspicious, it makes sense.

Here is the deal: it's encoding a ` Literal Header Field without Indexing — Indexed Name` that has  a 4-bit prefix thus you'll also see a 4bit at the end. Maybe there is something going wrong in the Huffman encoding.

**Comment by nesQuick** [comment]
GOT IT!

**Comment by nesQuick** [comment]
Will upload the patch asap and then we can rebase and merge this PR

**Comment by nesQuick** [comment]
merged with e80f6e98c0752bb2f2292547686a399449a3c8a3

**Pull request closed without merging**
